exadel-inc/CompreFace

README.md

EFRS-518: Added api description for delete model from MongoDB endpoint

---

ui/src/app/core/user/user.service.ts
ui/src/app/features/app-user-list/application-user-list-facade.ts
ui/src/app/features/user-list/user-list-facade.ts

Forgotten about application-user-facade from here
https://git.exadel.com/exadel-face-recognition-service/frs-mono/-/commit/bb6677dbe1bfe1ad480c49eb66c2c207a4fca589

EFRS-460 Change roles order in the list on the "Invite" pop-up

---

api/src/main/java/com/exadel/frs/core/trainservice/dao/ModelDao.java

EFRS-628: 400 Bad Request error occurs when try to update_model_key for not trained model

---

ui/README.md

I did it on my own. Please tell me if something missed

EFRS-670 : Update readme

---

ui/src/app/features/user-table/user-table.component.html

ADMIN and USER roles should be able to remove themselves from organization and application

EFRS-667 ADMIN and USER roles should be able to remove themselves from organization and application

---

dev/start--dev.sh
dev/start.sh
ui/src/app/features/footer/footer.component.html
ui/src/app/features/footer/footer.component.ts
ui/src/app/features/login-form/login-form.component.html
ui/src/app/features/login-form/login-form.component.scss
ui/src/app/features/login-form/login-form.component.ts
ui/src/environments/environment.dev.ts
ui/src/environments/environment.docker.ts
ui/src/environments/environment.local.ts
ui/src/environments/environment.prod.ts
ui/src/environments/environment.qa.ts
ui/src/environments/environment.ts
ui/src/environments/interface.ts

ACCORDING to the last discuss with Sergii Pospielov:
build number should consist of - hardcoded in file build number and hash of the last commit;
NOT READY for the case: ( for me )
- get hash of commit and replace variable;
because: " in that, we are replacing in  case %COMMIT_HASH% - source file, and we should reset file changes before every commit"

EFRS-420 Add actual version (build) number on footer

---

.github/workflows/cla.yml
CLA.md
README.md
workflows/cla.yml

Link to CLA.md will be available only after merging into the master branch. Or need to change the CLA.md url with develop branch link.

EFRS-732: Add CLA to github

---

embedding-calculator/requirements.txt

updated tensorflow version

---

.github/workflows/cla.yml

Use not protected branch to store signatures

---

api/src/test/java/com/exadel/frs/core/trainservice/component/FaceClassifierPredictorTest.java

https://jira.exadel.com/browse/EFRS-794

EFRS-794: FaceClassifierPredictor verify test added

---

ui/src/app/features/face-recognition/recognition-result/recognition-result.component.html
ui/src/app/features/face-recognition/recognition-result/recognition-result.component.ts
ui/src/app/store/app-user/effects.ts

Fixed updating user list under application, and updated logic for drawing the canvas under face recognition result

EFRS-779 Fixed updating user list under application

---

dev/.env
dev/Dockerfile
dev/docker-compose.yml

https://jira.exadel.com/browse/EFRS-792

EFRS-792:JVM options in env file

---

ui/src/app/features/face-recognition/recognition-result/recognition-result.component.ts
ui/src/app/store/face-recognition/selectors.ts
ui/src/app/store/user/effects.ts

re-opened issue EFRS-837 was fixed in this issue as well, because it was overwritten in develop.

EFRS-839: Recognize all faces and get result on the UI for all faces when there is more than 1 face on the image

---

ui/src/app/features/drag-n-drop/drag-n-drop.component.ts

wrong error message was fixed in previous issue. Here fixed console error in case of Cancel file event.

EFRS-830: Demo page and Test model page have error message when cancel adding a photo

---

admin/src/main/java/com/exadel/frs/service/AppService.java
admin/src/test/java/com/exadel/frs/AppServiceTest.java

…ull access to actions with applications

EFRS-886: User with Org Admin role have not full access to actions with applications

---

admin/src/main/java/com/exadel/frs/system/security/AuthorizationManager.java
admin/src/test/java/com/exadel/frs/system/security/AuthorizationManagerTest.java

- fixed user's privileges according to requirements

EFRS-887: Different logic on UI and Backend for Global User - App Admin

---

admin/src/main/java/com/exadel/frs/system/security/AuthorizationManager.java
admin/src/test/java/com/exadel/frs/system/security/AuthorizationManagerTest.java

- do not allow to Org Owner/Admin to delete App Owner from the app

EFRS-884: User_1 (Org Owner/App Admin) can delete User_2 (Org Admin,User/App Owner) with API request

---

ui/src/styles.scss

EFRS-918 - Fixed container resize

---

ui/src/app/core/constants.ts
ui/src/app/features/face-recognition/face-recognition-container.component.ts
ui/src/app/features/face-recognition/face-recognition.helpers.ts
ui/src/assets/i18n/en.json
ui/src/assets/i18n/pl.json

Added the error message when trying to upload an image with an unavailable extension

---

ui/src/app/core/face-recognition/face-recognition.service.ts
ui/src/app/data/interfaces/request-info.ts
ui/src/app/data/interfaces/response-result.ts
ui/src/app/data/interfaces/ui-request-options.ts
ui/src/app/features/face-recognition/face-recognition-container.component.html
ui/src/app/features/face-recognition/face-recognition.helpers.ts
ui/src/app/features/face-recognition/recognition-result/recognition-result.component.html
ui/src/app/features/face-recognition/recognition-result/recognition-result.component.ts
ui/src/app/store/face-recognition/selectors.ts

**Task** - [Update request and response info in test and demo pages](https://jira.exadel.com/browse/EFRS-903)

Updated request and response info in test and demo pages

---

admin/src/main/java/com/exadel/frs/entity/Model.java
admin/src/main/java/com/exadel/frs/enums/AppModelAccess.java
admin/src/main/java/com/exadel/frs/enums/AppRole.java
admin/src/main/java/com/exadel/frs/enums/EnumCode.java
admin/src/main/java/com/exadel/frs/enums/GlobalRole.java
admin/src/main/java/com/exadel/frs/enums/ModelType.java
admin/src/main/java/com/exadel/frs/exception/IncorrectModelTypeException.java
admin/src/main/java/com/exadel/frs/handler/ExceptionCode.java
admin/src/main/java/com/exadel/frs/helpers/AppRoleConverter.java
admin/src/main/java/com/exadel/frs/helpers/EnumCodeConverter.java
admin/src/main/java/com/exadel/frs/helpers/GlobalRoleConverter.java
admin/src/main/java/com/exadel/frs/helpers/ModelAccessTypeConverter.java
admin/src/main/java/com/exadel/frs/helpers/ModelTypeConverter.java
admin/src/main/java/com/exadel/frs/service/ModelService.java
admin/src/main/java/com/exadel/frs/validation/EnumValidator.java
admin/src/main/resources/db/changelog/db.changelog-0.1.4.yaml
admin/src/main/resources/db/changelog/db.changelog-master.yaml
admin/src/test/java/com/exadel/frs/helpers/ModelTypeConverterTest.java
admin/src/test/java/com/exadel/frs/validation/EnumValidatorTest.java

- added liquibase migrations
- added ModelType to Model entities and DTOs
- added EnumCode and EnumCodeConverter classes for easier enum conversions
- refactored exception codes for wrong DB conversion - it's 500
- refactored EnumValidator
- added Unit tests
- refactored converters for existing enumerations

EFRS-889 - add type to model

---

ui/src/app/core/model/model.service.ts
ui/src/app/features/model-clone-dialog/model-clone-dialog.component.html
ui/src/app/features/model-clone-dialog/model-clone-dialog.component.scss
ui/src/app/features/model-clone-dialog/model-clone-dialog.component.ts
ui/src/app/features/model-list/model-list-facade.ts
ui/src/app/features/model-list/model-list.component.html
ui/src/app/features/model-list/model-list.component.ts
ui/src/app/features/model-table/model-table.component.html
ui/src/app/features/model-table/model-table.component.ts
ui/src/app/features/model-table/model-table.module.ts
ui/src/app/store/model/actions.ts
ui/src/app/store/model/effects.ts
ui/src/app/store/model/reducers.ts
ui/src/assets/i18n/en.json
ui/src/assets/i18n/pl.json

**Task** - [Add ability to clone face collections UI part](https://jira.exadel.com/browse/EFRS-847)

EFRS-847 - Added ability to clone face collections on UI

---

ui/src/app/core/user/user.service.ts
ui/src/app/data/interfaces/user-deletion.ts
ui/src/app/features/delete-dialog/delete-dialog.component.html
ui/src/app/features/user-list/user-list-facade.ts
ui/src/app/features/user-list/user-list.component.ts
ui/src/app/features/user-table/user-table.component.ts
ui/src/app/store/user/action.ts
ui/src/app/store/user/effects.ts
ui/src/assets/i18n/en.json
ui/src/assets/i18n/pl.json

**Task** - [Organization side: It is impossible to choose the Owner of inherited application after deleting user](https://jira.exadel.com/browse/EFRS-952)

EFRS-952 - Fixed logic to choose the Owner of an inherited application after deleting the user

---

admin/pom.xml
admin/src/main/java/com/exadel/frs/controller/ModelController.java
admin/src/main/java/com/exadel/frs/dto/ui/ModelCloneDto.java
admin/src/main/java/com/exadel/frs/entity/AppModel.java
admin/src/main/java/com/exadel/frs/entity/Face.java
admin/src/main/java/com/exadel/frs/entity/Image.java
admin/src/main/java/com/exadel/frs/entity/Model.java
admin/src/main/java/com/exadel/frs/entity/User.java
admin/src/main/java/com/exadel/frs/repository/FacesRepository.java
admin/src/main/java/com/exadel/frs/repository/ImagesRepository.java
admin/src/main/java/com/exadel/frs/service/ModelService.java
admin/src/main/java/com/exadel/frs/service/UserService.java
admin/src/main/resources/db/changelog/db.changelog-0.1.5.yaml
admin/src/main/resources/db/changelog/db.changelog-master.yaml
admin/src/test/java/com/exadel/frs/ModelServiceTest.java
admin/src/test/java/com/exadel/frs/controller/ModelControllerTest.java
admin/src/test/java/com/exadel/frs/controller/UserControllerTest.java

I have read the CLA Document and I hereby sign the CLA

EFRS-957: return clone and isAllowStatistics functionality

---

admin/src/main/java/com/exadel/frs/entity/Model.java
ui/src/app/features/model-clone-dialog/model-clone-dialog.component.html
ui/src/app/features/model-list/model-list.component.ts
ui/src/app/features/model-table/model-table.component.html

**Task** - [Add ability to clone face collections UI part](https://jira.exadel.com/browse/EFRS-847)

EFRS-847 - Enabled to the ability to clone model on UI

---

ui/src/app/core/user-info/user-info.service.ts
ui/src/app/data/interfaces/delete-user.ts
ui/src/app/data/interfaces/edit-user-info.ts
ui/src/app/data/interfaces/update-user-role.ts
ui/src/app/data/interfaces/user-info.ts
ui/src/app/features/edit-user-info-dialog/edit-user-info-dialog.component.html
ui/src/app/features/edit-user-info-dialog/edit-user-info-dialog.component.scss
ui/src/app/features/edit-user-info-dialog/edit-user-info-dialog.component.spec.ts
ui/src/app/features/edit-user-info-dialog/edit-user-info-dialog.component.ts
ui/src/app/features/edit-user-info-dialog/edit-user-info-dialog.module.ts
ui/src/app/features/tool-bar/tool-bar.component.html
ui/src/app/features/tool-bar/tool-bar.component.ts
ui/src/app/features/tool-bar/tool-bar.container.component.ts
ui/src/app/features/tool-bar/tool-bar.facade.ts
ui/src/app/features/tool-bar/tool-bar.module.ts
ui/src/app/store/application/action.ts
ui/src/app/store/application/reducers.ts
ui/src/app/store/application/selectors.ts
ui/src/app/store/user/action.ts
ui/src/app/store/user/reducers.ts
ui/src/app/store/userInfo/action.ts
ui/src/app/store/userInfo/effects.ts
ui/src/app/store/userInfo/reducers.ts
ui/src/app/store/userInfo/user.reducers.spec.ts
ui/src/assets/i18n/en.json
ui/src/assets/i18n/pl.json

**Task** -  [Add modal with account settings](https://jira.exadel.com/browse/EFRS-848)

EFRS-848 - Added ability to change a user name

---

admin/src/main/java/com/exadel/frs/mapper/UserAppRoleMapper.java

UserRoleResponseDto mapping corrected: email is mapped from source's user member

UserRoleResponseDto mapping improved: added email mapping

---

admin/pom.xml
admin/src/test/java/com/exadel/frs/EmbeddedPostgreSQLTest.java
admin/src/test/java/com/exadel/frs/UserServiceTestIT.java
admin/src/test/java/com/exadel/frs/handler/ResponseExceptionHandlerTest.java
admin/src/test/java/com/exadel/frs/security/OAuthMvcTest.java
admin/src/test/java/com/exadel/frs/validation/ValidatorTest.java
admin/src/test/resources/application.yml

I have read the CLA Document and I hereby sign the CLA

EFRS-957: added embedded PostgreSQL for tests

---

ui/src/app/app-routing.module.ts
ui/src/app/app.module.ts
ui/src/app/core/user-info/user-info.resolver.ts
ui/src/app/pages/dashboard/dashboard.component.ts
ui/src/app/ui/demo-layout/demo-layout.component.html
ui/src/app/ui/demo-layout/demo-layout.component.spec.ts
ui/src/app/ui/demo-layout/demo-layout.component.ts

**Task** - [Page of Organization side is shown for 1 second when user is not log in](https://jira.exadel.com/browse/EFRS-919)

EFRS-919 - fixed unexpected behavior: when a user is not logged in the main page is seen during 1 second

---

README.md

Information about age and gender fields added to README REST API doc

Efrs 914 add age gender documentation

---

README.md
dev/README.md
dev/start--dev.sh
dev/start.sh
ui/README.md
ui/scripts/down.sh
ui/scripts/restart.sh
ui/scripts/start.sh
ui/scripts/startWin.sh

**Task** - [Update local start and readme](https://jira.exadel.com/browse/EFRS-943)

EFRS-943 - Updated local start and readme

---

api/src/test/java/com/exadel/frs/core/trainservice/controller/DetectionControllerTest.java
ui/src/app/core/face-recognition/face-recognition.service.ts

FE side corrected to use changed REST endpoint

Efrs 965 detection endpoint modification

---

.github/workflows/Saving-visitors-statistics-to-S3.yml

I have read the CLA Document and I hereby sign the CLA

EFRS 942 add Statistics to s3

---

README.md
java/admin/src/main/java/com/exadel/frs/dto/ui/ChangePasswordDto.java
java/admin/src/main/java/com/exadel/frs/dto/ui/UserUpdateDto.java
java/api/src/main/java/com/exadel/frs/core/trainservice/controller/VerifyController.java
java/api/src/main/java/com/exadel/frs/core/trainservice/dto/VerifyFacesResponse.java
java/api/src/main/java/com/exadel/frs/core/trainservice/dto/VerifyFacesResultDto.java
java/api/src/main/java/com/exadel/frs/core/trainservice/mapper/FacesMapper.java

Face plugin info(age, gender, landmarks) added to the response class from endpoint _api/v1/verify_

Efrs 940 return face plugin info from all services

---

java/admin/src/main/java/com/exadel/frs/controller/AppController.java
java/admin/src/main/java/com/exadel/frs/controller/ModelController.java
java/admin/src/main/java/com/exadel/frs/dto/ui/ModelResponseDto.java
java/admin/src/main/java/com/exadel/frs/mapper/MlModelMapper.java
java/admin/src/main/java/com/exadel/frs/repository/FacesRepository.java
java/admin/src/main/java/com/exadel/frs/repository/ImagesRepository.java
java/admin/src/main/java/com/exadel/frs/service/AppService.java
java/admin/src/main/java/com/exadel/frs/service/ModelService.java
java/admin/src/main/java/com/exadel/frs/service/UserService.java
java/admin/src/main/resources/db/changelog/db.changelog-0.1.6.yaml
java/admin/src/test/java/com/exadel/frs/AppServiceTest.java
java/admin/src/test/java/com/exadel/frs/ModelServiceTest.java
java/admin/src/test/java/com/exadel/frs/controller/AppControllerTest.java
java/admin/src/test/java/com/exadel/frs/controller/ModelControllerTest.java
java/api/src/main/java/com/exadel/frs/core/trainservice/repository/FacesRepository.java
java/api/src/main/java/com/exadel/frs/core/trainservice/repository/ImagesRepository.java
java/common/src/main/java/com/exadel/frs/commonservice/entity/App.java

I have done some cleaning stuff, removed unneeded code. After that I have tried to launch the project from the beginning, it worked. And I have tried to build java module and build passed successfully.

removed unneeded redundant code, some code reformatting made

---

java/api/src/main/java/com/exadel/frs/core/trainservice/dto/FacePredictionResultDto.java
java/api/src/main/java/com/exadel/frs/core/trainservice/dto/FaceSimilarityDto.java
java/api/src/main/java/com/exadel/frs/core/trainservice/dto/FacesBox.java
java/api/src/main/java/com/exadel/frs/core/trainservice/dto/FacesDetectionResponseDto.java
java/api/src/main/java/com/exadel/frs/core/trainservice/dto/FacesRecognitionResponseDto.java
java/api/src/main/java/com/exadel/frs/core/trainservice/dto/PluginsVersionsDto.java
java/api/src/main/java/com/exadel/frs/core/trainservice/dto/VerifyFacesResponse.java
java/api/src/main/java/com/exadel/frs/core/trainservice/dto/VerifyFacesResultDto.java
java/common/src/main/java/com/exadel/frs/commonservice/dto/FindFacesResultDto.java

From now on fields with null value not included in face service responses

Fields with null value not included

---

java/admin/src/main/java/com/exadel/frs/service/ModelService.java
java/api/src/main/java/com/exadel/frs/core/trainservice/filter/SecurityValidationFilter.java
java/api/src/test/java/com/exadel/frs/core/trainservice/filter/SecurityValidationFilterTest.java
java/common/src/main/java/com/exadel/frs/commonservice/exception/BadFormatModelKeyException.java
java/common/src/main/java/com/exadel/frs/commonservice/exception/ModelNotFoundException.java

Updated error messages when face services is not found

Updated error message when service is not found

---

java/api/src/test/java/com/exadel/frs/core/trainservice/filter/SecurityValidationFilterTest.java

Some tests with Security validation filter improved

security validation filter test improved

---

java/api/src/main/java/com/exadel/frs/core/trainservice/dto/FacePredictionResultDto.java
java/api/src/main/java/com/exadel/frs/core/trainservice/dto/FaceSimilarityDto.java
java/api/src/main/java/com/exadel/frs/core/trainservice/service/FaceRecognizeProcessServiceImpl.java
java/api/src/test/java/com/exadel/frs/core/trainservice/controller/RecognizeControllerTest.java

In face recognition response faces field renamed to subjects and inside faces object, face_name field renamed to subject

face field renamed to subject

---

ui/package.json

(holding a Angular CDK version on a 11.0.3 and not highest, equivalent to angular/material version)

FIX according to issue with "export 'isFakeTouchstartFromScreenReader'"

---

java/api/src/main/java/com/exadel/frs/core/trainservice/controller/RecognizeController.java

Recognition service prediction count parameter improved

prediction count validation annotation removed

---

java/api/src/main/java/com/exadel/frs/core/trainservice/service/SubjectService.java

Adding remove case when  subject name is blank

---

embedding-calculator/src/services/facescan/plugins/facenet/facenet.py
embedding-calculator/src/services/facescan/plugins/insightface/facemask/facemask.py
embedding-calculator/src/services/facescan/scanner/test/test_embedder.py

Changes:
1. Fixed gpu support in insightface/facemask
2. New margins for facenet face alignemnt

Efrs 1098 facemask gpu

---

ui/.husky/pre-commit
ui/package.json

Automatic pre-commit hook which runs prettier on staged files. It eliminates styling problems for future development. 
Build upon [husky](https://github.com/typicode/husky) and [pretty-quick](https://github.com/azz/pretty-quick).

Husky hooks

---

ui/src/app/features/mode-create-dialog/model-create-dialog.component.html

I've worked on focusing input while you create new Service, by adding cdkFocusInitial attr to input and removing from button.
resolve Issue: #614

[Solve] Input is focused when you creat new Service

---

ui/src/app/features/create-dialog/create-dialog.component.html

I've worked on focusing input while you create new Application, by adding cdkFocusInitial attr to input and removing from button.
resolve Issue: #613

[Solve] Input is focused when you create new Application

---

ui/src/app/features/user-table/user-table.component.ts

fixed issue with opening application if the owner of the application is not the same person

EFRS-1182/BugFix 

---

java/admin/src/main/java/com/exadel/frs/system/global/Constants.java
java/admin/src/main/java/com/exadel/frs/system/security/endpoint/CustomTokenEndpoint.java
java/admin/src/test/java/com/exadel/frs/system/security/endpoint/CustomTokenEndpointTest.java

Added ability to refresh the session

EFRS-1183: Added ability to refresh the session

---

java/admin/src/main/java/com/exadel/frs/controller/ConfigController.java
java/admin/src/main/java/com/exadel/frs/dto/ui/ConfigDto.java
java/admin/src/main/java/com/exadel/frs/system/security/config/ResourceServerConfig.java
java/admin/src/main/java/com/exadel/frs/system/security/config/WebSecurityConfig.java

Added ConfigController to be able to check whether a mail service is enabled or not for the Admin microservice

EFRS-1293: Added ConfigController for the Admin microservice

---

.github/workflows/Build-Deploy-auto.yml

Triggering build/deploy action on 1.1.x branch

Add CI/CD action to the branch

---

dev/docker-compose.env.yml
dev/nginx/conf.d/nginx.conf

(cherry picked from commit fe004d0f265b7aa14cd5eb86821f5d41778c3efc)

ERFS-1329 Deploy app to the Project envs [1.1.x]

---

.github/workflows/unit-tests-on-maven.yml

The action is triggered on each pull request and push to the master branch

EFRS-1336 Add action for Maven unit tests

---

.env
custom-builds/FaceNet/.env
custom-builds/FaceNet/docker-compose.yml
custom-builds/Mobilenet-gpu/.env
custom-builds/Mobilenet-gpu/docker-compose.yml
custom-builds/Mobilenet/.env
custom-builds/Mobilenet/docker-compose.yml
custom-builds/SubCenter-ArcFace-r100-gpu/.env
custom-builds/SubCenter-ArcFace-r100-gpu/docker-compose.yml
custom-builds/SubCenter-ArcFace-r100/.env
custom-builds/SubCenter-ArcFace-r100/docker-compose.yml
docker-compose.yml

I have read the CLA Document and I hereby sign the CLA

EFRS-1082: Added max_detect_size variable

---

.github/workflows/load-tests-k6.yml

- EFRS-1345 Add gh action for load tests
- register forkflow

EFRS-1345 Add gh action for load tests

---

.github/workflows/Release-default.yml
dev/docker-compose.multiplatform.yml
dev/docker-compose.yml
ui/docker-prod/Dockerfile

Release build with multi platform images.

[Release] Build and Push multi platform images (amd64, arm64)

---

dev/docker-compose-gpu.yml
dev/docker-compose.yml
docker-compose.yml
embedding-calculator/src/_endpoints.py

The first api call lasts too long time, because you need to wait until model loading

Early init of model

---

ui/src/app/features/collection-manager-subject-right/collection-manager-subject-right/collection-manager-subject-right.component.ts
ui/src/app/features/create-application/application/application-name.component.ts
ui/src/app/features/model-clone-dialog/model-clone-dialog.component.html
ui/src/app/features/model-clone-dialog/model-clone-dialog.component.ts
ui/src/app/features/model-info/model-info.component.html
ui/src/app/features/model-table/model-table.component.html
ui/src/app/features/sign-up-form/sign-up-form.component.html
ui/src/app/store/manage-collectiom/effects.ts
ui/src/app/store/model/effects.ts

Fixes UI Bugs mention in these tickets:
EFRS-1392
EFRS-1399
EFRS-1484
EFRS-1495
EFRS-1521

UI Bug Fixes
